# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ejemplo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ejemplo.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rejemplo.proto\"0\n\x05Trend\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05score\x18\x02 \x02(\x05\x12\n\n\x02ok\x18\x07 \x02(\x08\"%\n\x08\x43onjunto\x12\x19\n\ttendencia\x18\x01 \x03(\x0b\x32\x06.Trend\"\x1d\n\x05Vista\x12\x14\n\x01\x63\x18\x01 \x03(\x0b\x32\t.Conjunto')
)




_TREND = _descriptor.Descriptor(
  name='Trend',
  full_name='Trend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Trend.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='Trend.score', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ok', full_name='Trend.ok', index=2,
      number=7, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=65,
)


_CONJUNTO = _descriptor.Descriptor(
  name='Conjunto',
  full_name='Conjunto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tendencia', full_name='Conjunto.tendencia', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=104,
)


_VISTA = _descriptor.Descriptor(
  name='Vista',
  full_name='Vista',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='c', full_name='Vista.c', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=135,
)

_CONJUNTO.fields_by_name['tendencia'].message_type = _TREND
_VISTA.fields_by_name['c'].message_type = _CONJUNTO
DESCRIPTOR.message_types_by_name['Trend'] = _TREND
DESCRIPTOR.message_types_by_name['Conjunto'] = _CONJUNTO
DESCRIPTOR.message_types_by_name['Vista'] = _VISTA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Trend = _reflection.GeneratedProtocolMessageType('Trend', (_message.Message,), {
  'DESCRIPTOR' : _TREND,
  '__module__' : 'ejemplo_pb2'
  # @@protoc_insertion_point(class_scope:Trend)
  })
_sym_db.RegisterMessage(Trend)

Conjunto = _reflection.GeneratedProtocolMessageType('Conjunto', (_message.Message,), {
  'DESCRIPTOR' : _CONJUNTO,
  '__module__' : 'ejemplo_pb2'
  # @@protoc_insertion_point(class_scope:Conjunto)
  })
_sym_db.RegisterMessage(Conjunto)

Vista = _reflection.GeneratedProtocolMessageType('Vista', (_message.Message,), {
  'DESCRIPTOR' : _VISTA,
  '__module__' : 'ejemplo_pb2'
  # @@protoc_insertion_point(class_scope:Vista)
  })
_sym_db.RegisterMessage(Vista)


# @@protoc_insertion_point(module_scope)
